### ISSUE TITLE
Keep Running Even There Is Failed Exposure in MultiExposure Analysis

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe-headless#25]
In multi exposure analysis, there is a case where the exposure doens't work with the hazard (no feature or some other error) but works for the other exposures.

Headless needs to keep running the analysis (removing the bad exposure).

**Comment by Gustry** [comment]
And also warn the dev about this missing exposure in the report. Must be considered as a bug, just a workaround to skip it

**Comment by ismailsunni** [comment]
@Gustry will it send error message to sentry (after you merge your PR) ?

**Comment by lucernae** [comment]
@ismailsunni please close if this is resolved.

**Comment by ismailsunni** [comment]
Not really, I think we haven't got time to address this issue since it happens in a corner case.

**Comment by lucernae** [comment]
I will close this.
