### ISSUE TITLE
Better Setup for Testing with InaSAFE-Django

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe-headless#34]
Currently, we need to tweak some parts to make inasafe-django works properly with local inasafe-headless.

- [ ] We should make it easier by using the same path mapping in inasafe-headless.
- [ ] We should write a README/wiki for doing this also.

**Comment by lucernae** [comment]
I think we already make this better using ansible setup. Howzit, @ismailsunni ?

**Comment by ismailsunni** [comment]
Yes, I think we are done. Thanks
